from qdrant_client import QdrantClient, models

from models import Chunk, chunk_retrieval_text

DENSE_VECTOR_NAME = "dense"
SPARSE_VECTOR_NAME = "bm25"
EMBEDDING_DIM = 1536  # OpenAI text-embedding-3-small
COLLECTION_NAME = "code_chunks"
QDRANT_URL = "http://localhost:6333"


def init_client(url: str | None = None) -> QdrantClient:
    """Connect to Qdrant: `path=` for an embedded local instance, `url=` for a real server."""
    if url is not None:
        return QdrantClient(url=url)
    raise ValueError("init_client requires url")


def upsert_chunks(client: QdrantClient, collection_name: str, chunks: list[Chunk]) -> None:
    """Upsert every chunk's dense vector, sparse (BM25) vector, and payload.

    The sparse vector is generated by Qdrant itself.
    """
    points = [
        models.PointStruct(
            id=chunk.id,
            vector={
                DENSE_VECTOR_NAME: chunk.embedding,
                SPARSE_VECTOR_NAME: models.Document(
                    text=chunk_retrieval_text(chunk), model="bm25"
                ),
            },
            payload={
                "file_path": str(chunk.path),
                "language": chunk.language,
                "kind": chunk.kind,
                "class_name": chunk.class_name,
                "symbol_name": chunk.symbol_name,
                "start_byte": chunk.start_byte,
                "end_byte": chunk.end_byte,
                "parent_id": chunk.parent_id,
                "content_hash": chunk.content_hash,
            },
        )
        for chunk in chunks
    ]
    client.upsert(collection_name=collection_name, points=points)


def ensure_collection(client: QdrantClient, name: str) -> None:
    """Create the `name` collection (dense + BM25 sparse vectors) if it doesn't already exist."""
    if client.collection_exists(name):
        return
    client.create_collection(
        collection_name=name,
        vectors_config={
            DENSE_VECTOR_NAME: models.VectorParams(
                size=EMBEDDING_DIM, distance=models.Distance.COSINE
            ),
        },
        sparse_vectors_config={
            SPARSE_VECTOR_NAME: models.SparseVectorParams(
                modifier=models.Modifier.IDF
            ),
        },
    )
